import type { Metadata } from "next";
import "./globals.css";
import { pretendard } from "@/assets/fonts";
import { Header } from "@/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body className={pretendard.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
