import type { Metadata } from "next";
import "./globals.css";
import { pretendard } from "@/assets/fonts";
import { Header, Providers } from "@/components";

export const metadata: Metadata = {
  title: "4rchive - Minseok's tech blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="light" style={{ colorScheme: "light" }}>
      <body
        className={`${pretendard.className} text-black dark:text-white bg-white dark:bg-black transition-[background] duration-200`}
      >
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
