import { AnimatedPage, TagsPageTemplate } from "@/components";
import { getAllPosts } from "@/lib/api";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "4rchive - Minseok's tech blog2",
  description: "Generated by create next app",
};

export default function Page() {
  const allPosts = getAllPosts([
    "slug",
    "title",
    "author",
    "date",
    "coverImage",
    "excerpt",
    "tags",
  ]);

  const setOfTags = new Set<string>();

  allPosts.forEach((post) => {
    if (post.tags) {
      post.tags.forEach((tag) => setOfTags.add(tag));
    }
  });

  const allTags: string[] = Array.from(setOfTags);

  return (
    <AnimatedPage>
      <TagsPageTemplate allPosts={allPosts} allTags={allTags} />
    </AnimatedPage>
  );
}
