import { Metadata } from "next";

export const metadata: Metadata = {
  title: "4rchive - Minseok's tech blog2",
  description: "Generated by create next app",
};

export default function Page() {
  return <></>;
}
